spring.application.name=Cart-Service

server.port=8084

#Context Path for this microservice
server.servlet.context-path=/cart

#Datasource Configuration
#Connection URL
spring.datasource.url=${datasource_url}
#Database credentials
spring.datasource.username=${datasource_username}
#spring.datasource.password=secret

#For service discovery
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${eureka_server}